name: test-and-coverage

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  cove-cov:
    runs-on: ubuntu-latest
    container: golang:1.22.0
     #env:
      #DATABASE_URL: "postgres://postgres:postgres@postgres:5432/praktikum?sslmode=disable"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: 1.22
        - name: Run coverage
          run: |
            go env -w CGO_ENABLED=0
            cd files_client_upload
            dd if=/dev/zero of=upload_test bs=1M count=1024
            cd ..
            make generate-keys-rsa
            make build-client
            go test -v -coverprofile coverage.out -coverpkg= ./test/... ./internal/...
            go tool cover -html coverage.out -o coverage.html
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.out
            flags: unittests
            name: codecov-umbrella
        - name: Archive code coverage results
          uses: actions/upload-artifact@v4
          with:
            name: code-coverage-report
            path: coverage.html